//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ekspedition
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryShipping
    {
        public int Id { get; set; }
        public int Shipping_Id { get; set; }
        public int Employee_Id { get; set; }
        public int StatusShipping_Id { get; set; }
    
        public virtual Shipping Shipping { get; set; }
    }
}
